default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: battlepets_management
  password: password1

development:
  <<: *default
  database: battlepets_management_development

test:
  <<: *default
  database: battlepets_management_test
